language: cpp
compiler: g++

env:
  global:
    - CXX=g++-4.8
  matrix:
    - CMAKE_BUILD_TYPE=Debug
    - CMAKE_BUILD_TYPE=Release
  matrix:
    - CONTRACTOR_DEFAULT_PROVER=contractor::prove_simple
    - CONTRACTOR_DEFAULT_PROVER=contractor::prove_clever
    - CONTRACTOR_DEFAULT_PROVER=contractor::prove_clever_lazy

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq g++-4.8
  - wget -qO- https://cmake.org/files/v3.4/cmake-3.4.3-Linux-x86_64.tar.gz | tar xvz

script: mkdir -p build && cd build && ./cmake-3.4.3-Linux-x86_64/bin/cmake .. -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} -DCONTRACTOR_DEFAULT_PROVER=${CONTRACTOR_DEFAULT_PROVER} && make && ./example && make test
